os:
- linux
addons:
  ssh_known_hosts:
  - portfolio.westeurope.cloudapp.azure.com
cache:
  directories:
  - "$HOME/.composer/cache"
language: php
php:
- '7.0'
install:
- composer install
script: vendor/bin/phpunit --configuration phpunit.xml --coverage-text
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $DEPLOY_USER@$DEPLOY_HOST:/home/christofer
  on:
    branch: master
notifications:
  email:
    recipients: christofer.malmberg@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_bcb8dddc1c9b_key -iv $encrypted_bcb8dddc1c9b_iv
  -in deploy_rsa.enc -out deploy_rsa -d
